name: Adsterra Bot

on:
  schedule:
    - cron: '*/15 * * * *'  # Toutes les 15 minutes
  workflow_dispatch:         # Permet un lancement manuel

jobs:
  run-bot:
    runs-on: ubuntu-latest   # Environnement d'exécution
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Run Adsterra Bot
      run: python visite_2.py
      
    - name: Save logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bot-logs-${{ github.run_id }}-${{ github.run_attempt }}
        path: |
          *.log
        retention-days: 7
